[package]
name = "sonos_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonor = "1.1"
confy = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"